import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { Toaster } from '@/components/ui/toaster';
import Link from 'next/link';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <div className='bg-slate-200'>
          <nav className='bg-slate-400 flex justify-center items-center'>
            <div className='grid lg:grid-cols-3 gap-5'>
              <Link
                href='/'
                className='rounded-lg px-5 py-4 transition-colors hover:border-gray-300 hover:bg-gray-100 flex justify-center items-center'
                rel='noopener noreferrer'
              >
                <h2 className={`text-2xl font-semibold`}>Home Page</h2>
              </Link>
              <Link
                href='/todo'
                className='rounded-lg px-5 py-4 transition-colors hover:border-gray-300 hover:bg-gray-100 flex justify-center items-center'
                rel='noopener noreferrer'
              >
                <h2 className={`text-2xl font-semibold`}>
                  To Do Page
                  <span className='inline-block transition-transform group-hover:translate-x-1 motion-reduce:transform-none ml-2'>
                    -&gt;
                  </span>
                </h2>
              </Link>
              <Link
                href='/auth-server-action'
                className='rounded-lg px-5 py-4 transition-colors hover:border-gray-300 hover:bg-gray-100 flex justify-center items-center'
                rel='noopener noreferrer'
              >
                <h2 className={`text-2xl font-semibold`}>
                  Auth Server Action
                  <span className='inline-block transition-transform group-hover:translate-x-1 motion-reduce:transform-none ml-2'>
                    -&gt;
                  </span>
                </h2>
              </Link>
            </div>
          </nav>
          <div className='-mt-20'>
            {children} <Toaster />
          </div>
        </div>
      </body>
    </html>
  );
}
